### ISSUE TITLE
ko_KR OCONV table crashes

### ISSUE THREAD

**Issue by changwoo** [hunspell/hunspell#411]
The latest git version crashes on ko_KR. (1.4.0 is OK.) So I did some debugging and found the minimal aff file which crashed it.

```
COM:~hacks/spell/hunspell$ cat kotest.dic 
0
COM:~/hacks/spell/hunspell$ cat kotest.aff
SET UTF-8
OCONV 2
OCONV GA Ga
OCONV GAG Gag
```

Here is the stack trace.

```
COM:~/hacks/spell/hunspell$ ./libtool --mode=execute gdb ./src/tools/hunspell
(gdb) r -d kotest
Starting program: /home/cwryu/hacks/spell/hunspell/src/tools/.libs/lt-hunspell -d kotest

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bafe65 in RepList::add (this=0x62c000, in_pat1="GAG", pat2="Gag") at replist.cxx:176
176       for (int j = i - 2; j && !strncmp(dat[i-1]->pattern.c_str(), dat[j]->pattern.c_str(), dat[i-1]->pattern.size()); --j)
(gdb) where
#0  0x00007ffff7bafe65 in RepList::add (this=0x62c000, in_pat1="GAG", pat2="Gag") at replist.cxx:176
#1  0x00007ffff7b87665 in AffixMgr::parse_convtable (this=this@entry=0x62c400, line="OCONV 2", af=af@entry=0x63e700, rl=rl@entry=0x62e4d8, keyword="OCONV") at affixmgr.cxx:3886
#2  0x00007ffff7b8ce55 in AffixMgr::parse_file (this=this@entry=0x62c400, affpath=<optimized out>, key=<optimized out>) at affixmgr.cxx:553
#3  0x00007ffff7b8ddd4 in AffixMgr::AffixMgr (this=0x62c400, affpath=<optimized out>, ptr=..., key=<optimized out>) at affixmgr.cxx:173
#4  0x00007ffff7b9a0b4 in HunspellImpl::HunspellImpl (this=0x62bc20, affpath=0x62b810 "./kotest.aff", dpath=0x62bbe0 "./kotest.dic", key=0x0) at hunspell.cxx:170
#5  0x00007ffff7b9a202 in Hunspell::Hunspell (this=0x62bc00, affpath=0x62b810 "./kotest.aff", dpath=0x62bbe0 "./kotest.dic", key=0x0) at hunspell.cxx:156
#6  0x00000000004037dd in main (argc=3, argv=0x7fffffffe3b8) at hunspell.cxx:2073
(gdb) p j
$1 = -1
(gdb) p i
$2 = 1
```

**Comment by dimztimz** [comment]
Should be fixed, please test with latest master.
