### ISSUE TITLE
`-l -r` combination always crashes

### ISSUE THREAD

**Issue by jpouellet** [hunspell/hunspell#492]
The options in question (from man page):
```
       -l     The  "list" option is used to produce a list of misspelled words
              from the standard input.

       -r     Warn  of  the  rare words, wich are also potential spelling mis‐
              takes.
```

My system hunspell (old):
```
% hunspell --version
@(#) International Ispell Version 3.2.06 (but really Hunspell 1.3.3)


Copyright (C) 2002-2014 László Németh. License: MPL/GPL/LGPL.

Based on OpenOffice.org's Myspell library.
Myspell's copyright (C) Kevin Hendricks, 2001-2002, License: BSD.

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE,
to the extent permitted by law.
% echo foo | hunspell -l -r
zsh: done                              echo foo | 
zsh: segmentation fault (core dumped)  hunspell -l -r
```

Latest hunspell from master (currently d608646a1099ddabbba0457a77b8135bd4c7a659) built with debug symbols:
```
% gdb ~/hunspell/src/tools/.libs/lt-hunspell 
GNU gdb (GDB) Fedora 7.11.1-86.fc24
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/user/hunspell/src/tools/.libs/lt-hunspell...done.
(gdb) run -l -r
Starting program: /home/user/hunspell/src/tools/.libs/lt-hunspell -l -r
foo

Program received signal SIGSEGV, Segmentation fault.
0x0000000000408597 in check (pMS=0x7fffffffdd90, d=0x7fffffffba08, token="foo", info=0x0, root=0x0) at hunspell.cxx:608
608              !(warn && (*info & SPELL_WARN))) ||
(gdb) bt full
#0  0x0000000000408597 in check (pMS=0x7fffffffdd90, d=0x7fffffffba08, token="foo", info=0x0, root=0x0) at hunspell.cxx:608
        buf = "foo"
        i = 0
#1  0x000000000040940b in pipe_interface (pMS=0x7fffffffdd90, format=0, fileid=0x7ffff72858c0 <_IO_2_1_stdin_>, filename=0x0) at hunspell.cxx:802
        token = "foo"
        buf = "foo", '\000' <repeats 7205 times>...
        dicwords = std::vector of length 0, capacity 0
        pos = 0
        bad = 0
        lineno = 1
        terse_mode = 0
        verbose_mode = 0
        d = 0
        odftmpdir = 0x0
        extension = 0x0
        parser = 0xa8f620
        tmpdirtemplate = "/tmp/hunspellXXXXXX"
        bZippedOdf = false
#2  0x000000000040c77f in main (argc=3, argv=0x7fffffffdf68) at hunspell.cxx:2155
        buf = ".hunspell_en_US"
        pMS = {0x632cc0, 0x40dd48 <std::allocator<w_char>::allocator()+24>, 0x4000000000000000, 0x61fe50 <new_wordchars_utf16>, 0x7fffffffddd0, 
          0x40d65c <std::_Vector_base<w_char, std::allocator<w_char> >::_Vector_impl::_Vector_impl()+24>, 0x61fe30 <wordchars[abi:cxx11]+16>, 
          0x61fe50 <new_wordchars_utf16>, 0x7fffffffddf0, 0x40cfb2 <std::_Vector_base<w_char, std::allocator<w_char> >::_Vector_base()+24>}
        key = 0x0
        arg_files = -1
        format = 0
        argstate = 0
        dicplus = 0x0
        aff = 0x632c30 "/usr/share/myspell/en_US.aff"
        dic = 0x632c60 "/usr/share/myspell/en_US.dic"
```

**Comment by FlashSheridan** [comment]
Thanks for identifying -r as part of the problem; this was preventing us from using Hunspell in continuous integration.
