### ISSUE TITLE
Segmentation faults 2017-06-16

### ISSUE THREAD

**Issue by rwhitworth** [hunspell/hunspell#505]
Hello, I was using American Fuzzy Lop (afl-fuzz) to fuzz input to the `analyze` program on Linux. Is fixing the crashes from these input files something you're interested in? The input files can be found here: https://github.com/rwhitworth/hunspell-fuzz/tree/master/2017-06-16

The files can be executed as `./analyze id_filename IJ.dic IJ.good` to cause seg faults.

Let me know if I can provide any more information to help narrow down this issue.

```
# ./analyze id\:000016\,sig\:11\,src\:000080\,op\:havoc\,rep\:8 IJ.dic IJ.good ; gdb --batch --eval-command=bt ./analyze core
> ijs
analyze(ijs) =  st:ijs
stem(ijs) = ijs
> IJs
Unknown word.
Segmentation fault (core dumped)
[New LWP 21781]
Core was generated by `./analyze id:000016,sig:11,src:000080,op:havoc,rep:8 IJ.dic IJ.good'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __GI___libc_free (mem=0x10) at malloc.c:2929
2929    malloc.c: No such file or directory.
#0  __GI___libc_free (mem=0x10) at malloc.c:2929
#1  0x00007f805fbece30 in HashMgr::~HashMgr (this=0x215f340) at hashmgr.cxx:146
#2  0x00007f805fbfcc2f in HunspellImpl::~HunspellImpl (this=0x215f270) at hunspell.cxx:198
#3  0x00007f805fbfc96d in Hunspell::~Hunspell (this=<optimized out>) at hunspell.cxx:191
#4  0x0000000000402cc5 in main (argv=<optimized out>) at analyze.cxx:100
```

```
# ./analyze id\:000020\,sig\:11\,src\:000091\,op\:havoc\,rep\:16 IJ.dic IJ.good ; gdb --batch --eval-command=bt ./analyze core
> ijs
analyze(ijs) =  st:ijs
stem(ijs) = ijs
> IJs
Unknown word.
Segmentation fault (core dumped)
[New LWP 21792]
Core was generated by `./analyze id:000020,sig:11,src:000091,op:havoc,rep:16 IJ.dic IJ.good'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __GI___libc_free (mem=0x1) at malloc.c:2929
2929    malloc.c: No such file or directory.
#0  __GI___libc_free (mem=0x1) at malloc.c:2929
#1  0x00007f5c65173cc0 in HashMgr::~HashMgr (this=0x232a340) at hashmgr.cxx:136
#2  0x00007f5c65183c2f in HunspellImpl::~HunspellImpl (this=0x232a270) at hunspell.cxx:198
#3  0x00007f5c6518396d in Hunspell::~Hunspell (this=<optimized out>) at hunspell.cxx:191
#4  0x0000000000402cc5 in main (argv=<optimized out>) at analyze.cxx:100
```

**Comment by caolanm** [comment]
this particular example seems to be good in current trunk
